// Code generated by dirty-go; DO NOT EDIT.
package dirty_out

import (
	"encoding/json"
	"github.com/hanxi/dirty-go/dirty_tmpl"
)

type Wanfa1 struct {
	Base
	uame string
}

func NewWanfa1() *Wanfa1 {
	p := &Wanfa1{}
	p.self = p
	p.root = p
	return p
}

func (p *Wanfa1) SetUame(value string) {
	if p == nil {
		return
	}
	p.uame = value
	p.NotifyDirty()
}

func (p *Wanfa1) GetUame() string {
	if p == nil {
		return ""
	}
	return p.uame
}

func (p *Wanfa1) fromOrigin(o *dirty_tmpl.Wanfa1) {
	p.uame = o.Uame
}

func (p *Wanfa1) toOrigin() *dirty_tmpl.Wanfa1 {
	if p == nil {
		return nil
	}
	o := &dirty_tmpl.Wanfa1{}
	o.Uame = p.uame
	return o
}

func (p *Wanfa1) UnmarshalJSON(data []byte) error {
	origin := &dirty_tmpl.Wanfa1{}
	if err := json.Unmarshal(data, origin); err != nil {
		return err
	}
	p.fromOrigin(origin)
	return nil
}

func (p *Wanfa1) MarshalJSON() ([]byte, error) {
	origin := p.toOrigin()
	return json.Marshal(origin)
}
